#!/usr/bin/env bash

stage_dir=_sarsoo.xyz

echo '>> backing up a directory'
cd ..

echo '>> deleting old deployment stage'
rm -rf $stage_dir

echo '>> copying main source'
cp -r sarsoo.xyz $stage_dir

echo '>> injecting fmframework'
cp -r fmframework/fmframework $stage_dir/

cd $stage_dir

echo '>> building css'
sass --style=compressed src/scss/style.scss build/style.css

echo '>> building javascript'
npm run build

echo '>> deploying'
gcloud config set project sarsooxyz
gcloud app deploy
